import type { Dispatch, SetStateAction } from "react";
import type { AppState, BackupRecord, ConfigDoctorReport, ExternalChangeNotifyPayload, FileSnapshotBundle, Locale, McpServerConfig, ModelConfig, PreviewBundle, Profile, ProviderConfig } from "@shared/types";
import type { SkillDiscoveryPath, SkillEntry, SkillsScanReport } from "@shared/skillsStore";
import type { SkillsViewMode } from "../skillsWorkspace";
import type { TabId, PreviewFileId } from "../appOptions";
import type { BackupRecordsDialogState, ConfirmDialogState, DocumentViewerState } from "../dialogs";
import type { DiagnosticsState } from "../overviewDashboard";

export interface AppContext {
  state: AppState;
  savedState: AppState | null;
  locale: Locale;
  title: string;
  activeTab: TabId;
  setActiveTab: (tab: TabId) => void;
  diagnostics: DiagnosticsState;
  setDiagnostics: Dispatch<SetStateAction<DiagnosticsState>>;
  // Selected items
  selectedProvider: string;
  setSelectedProvider: Dispatch<SetStateAction<string>>;
  selectedModel: string;
  setSelectedModel: Dispatch<SetStateAction<string>>;
  selectedProfile: string;
  setSelectedProfile: Dispatch<SetStateAction<string>>;
  selectedMcpServer: string;
  setSelectedMcpServer: Dispatch<SetStateAction<string>>;
  selectedSkillPath: string;
  setSelectedSkillPath: Dispatch<SetStateAction<string>>;
  selectedSkill: string;
  setSelectedSkill: Dispatch<SetStateAction<string>>;
  skillsViewMode: SkillsViewMode;
  setSkillsViewMode: Dispatch<SetStateAction<SkillsViewMode>>;
  // Computed
  providerEntries: Array<[string, ProviderConfig]>;
  modelEntries: Array<[string, ModelConfig]>;
  profileEntries: Array<[string, Profile]>;
  mcpEntries: Array<[string, McpServerConfig]>;
  skillPathEntries: SkillDiscoveryPath[];
  skillEntries: SkillEntry[];
  sortedSkillPathEntries: SkillDiscoveryPath[];
  visibleSkillEntries: SkillEntry[];
  selectedProviderName: string;
  selectedModelName: string;
  selectedProfileName: string;
  selectedMcpServerName: string;
  selectedSkillPathId: string;
  selectedSkillData: SkillEntry | null;
  selectedSkillPathData: SkillDiscoveryPath | null;
  selectedProviderData: ProviderConfig | null;
  selectedModelData: ModelConfig | null;
  selectedProfileData: Profile | null;
  selectedMcpServerData: McpServerConfig | null;
  isProviderNameEditable: boolean;
  isProfileNameEditable: boolean;
  isMcpServerNameEditable: boolean;
  dirtyProviders: Set<string>;
  dirtyModels: Set<string>;
  dirtyProfiles: Set<string>;
  dirtyMcpServers: Set<string>;
  // State
  preview: PreviewBundle;
  setPreview: Dispatch<SetStateAction<PreviewBundle>>;
  skillsReport: SkillsScanReport | null;
  setSkillsReport: Dispatch<SetStateAction<SkillsScanReport | null>>;
  isSkillsLoading: boolean;
  setIsSkillsLoading: Dispatch<SetStateAction<boolean>>;
  documentViewer: DocumentViewerState | null;
  setDocumentViewer: Dispatch<SetStateAction<DocumentViewerState | null>>;
  backupRecordsDialog: BackupRecordsDialogState | null;
  setBackupRecordsDialog: Dispatch<SetStateAction<BackupRecordsDialogState | null>>;
  doctorReport: ConfigDoctorReport | null;
  setDoctorReport: Dispatch<SetStateAction<ConfigDoctorReport | null>>;
  fileSnapshot: FileSnapshotBundle | null;
  setFileSnapshot: Dispatch<SetStateAction<FileSnapshotBundle | null>>;
  error: string;
  setError: Dispatch<SetStateAction<string>>;
  notice: string;
  setNotice: Dispatch<SetStateAction<string>>;
  externalChange: ExternalChangeNotifyPayload | null;
  setExternalChange: Dispatch<SetStateAction<ExternalChangeNotifyPayload | null>>;
  isMcpImportOpen: boolean;
  setIsMcpImportOpen: Dispatch<SetStateAction<boolean>>;
  mcpImportDraft: string;
  setMcpImportDraft: Dispatch<SetStateAction<string>>;
  mcpImportInitialDraft: string;
  setMcpImportInitialDraft: Dispatch<SetStateAction<string>>;
  mcpTestingName: string;
  setMcpTestingName: Dispatch<SetStateAction<string>>;
  profileTestingName: string;
  setProfileTestingName: Dispatch<SetStateAction<string>>;
  isBackupRunning: boolean;
  setIsBackupRunning: Dispatch<SetStateAction<boolean>>;
  isWebDavTesting: boolean;
  setIsWebDavTesting: Dispatch<SetStateAction<boolean>>;
  isBackupPasswordVisible: boolean;
  setIsBackupPasswordVisible: Dispatch<SetStateAction<boolean>>;
  confirmDialog: ConfirmDialogState | null;
  setConfirmDialog: Dispatch<SetStateAction<ConfirmDialogState | null>>;
  // Handlers
  updateState: (updater: (draft: AppState) => void, options?: { persist?: boolean; recordHistory?: boolean; historySummary?: string }) => void;
  updateImmediateState: (updater: (draft: AppState) => void, options?: { recordHistory?: boolean; historySummary?: string }) => void;
  runAfterUnsavedHandled: (action: () => void | Promise<void>) => void;
  onSave: () => Promise<void>;
  persistState: (nextState: AppState) => Promise<void>;
  confirmDeleteResource: (resourceLabel: string, name: string) => Promise<boolean>;
  requestConfirm: (options: ConfirmDialogState) => Promise<boolean>;
  closeMcpImportDialog: () => void;
  requestCloseMcpImportDialog: () => void;
  refreshSkills: (draft?: AppState, options?: { silent?: boolean }) => Promise<void>;
  openDocumentViewer: (file: PreviewFileId) => void;
  runManualBackup: () => void;
  runWebDavTest: () => void;
  openKimiInTerminal: (profileName?: string) => void;
  runDoctor: (state: AppState) => void;
  openBackupRecords: () => void;
  deleteBackupRecord: (record: BackupRecord) => void;
  restoreBackupRecord: (record: BackupRecord) => void;
}
